simulation:
  data:
    dataset_name: CIFAR100
    batch_size:
      values:
        - 32
        - 64
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": (element["img"] / 255.).transpose(2, 0, 1),
          "y": element["fine_label"]
        }
  federation:
    client_count: 100
    fraction_fit: 0.1
    global_rounds: 20
    local_rounds: 1
  model:
    optimizer_name: FedAdam
    model_name: ResNet34
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      local:
        lr:
          values:
            - 1e-1
            - 1e-2
            - 1e-3
      global:
        lr:
          values:
            - 1e-1
            - 1e-2
        betas:
          - 0.9
          - 0.99
        eps: 0.0001
    model_architecture:
      repo_or_dir: 'pytorch/vision:v0.10.0'
      model: 'resnet34'
      pretrained: False
      out_features: 100
attack:
  data_access: 1.0
  message_access: server
  repetitions: 1
  attack_simulation:
    batch_size: 64
    optimizer_name: FedAvg
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv2d
          out_channels: 1000
          kernel_size:
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
        - type: Sigmoid
