wandb:
  dataset_name: MNIST
  model_name: CNN
simulation:
  batch_size: -1
  client_count: 4
  fraction_fit: 1
  global_rounds: 10
  learning_method:
    optimizer: SGD
    learning_rate: 0.02
  local_rounds: 10
dataset:
  name: MNIST
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"] / 255.,
        "y": element["label"]
      }
  splitter:
    alpha: 1
    percent_noniid: 25
model:
  criterion:
    type: CrossEntropyLoss
  layers:
    - type: Conv2d
      in_channels: 1
      out_channels: 32
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Conv2d
      in_channels: 32
      out_channels: 64
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Flatten
      start_dim: 0
      end_dim: -1
    - type: Linear
      in_features: 3136
      out_features: 512
    - type: ReLU
    - type: Linear
      in_features: 512
      out_features: 10
    - type: Softmax
      dim: 0
