simulation:
  batch_size: 8
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 20
  optimizer:
    optimizer_name: FedAdam
    local:
      lr: 0.2
    global:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 0.00000001
      weight_decay: 0
dataset:
  name: MNIST
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"].reshape(784) / 255.,
        "y": element["label"]
      }
model:
  name: 2NN
  criterion: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 784
      out_features: 200
    - type: ReLU
    - type: Linear
      in_features: 200
      out_features: 200
    - type: ReLU
    - type: Linear
      in_features: 200
      out_features: 200
    - type: ReLU
    - type: Linear
      in_features: 200
      out_features: 10
    - type: Softmax
      dim: -1
