simulation:
  data:
    dataset_name: Texas
    batch_size: -1
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["features"],
          "y": element["label"]
        }
  federation:
    client_count: 10
    fraction_fit: 1.0
    local_rounds: 1
  model:
    optimizer_name: SingleLayerFedNL
    model_name: Logistic Regression
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
    model_architecture:
      - type: Linear
        in_features: 6169
        out_features: 100
attack:
  data_access:
    steps:
      - 1.0
      - 0.1
      - 1.0
      - 0.1
      - 1.0
      - 0.1
      - 1.0
      - 0.1
  message_access:
    steps:
      - server
      - client
      - server
      - client
      - server
      - client
      - server
      - client
  aggregate_access: [1]
  repetitions: 3
  attack_simulation:
    batch_size:
      steps:
        - 512
        - 512
        - 64
        - 64
        - 256
        - 256
        - 64
        - 64
    optimizer_name: Adam
    optimizer_parameters:
      eps: 0.0001
    model_architecture:
      components:
        steps:
          - label: True
            loss: True
            activation: False
            gradient: False
            metrics: False
          - label: True
            loss: True
            activation: False
            gradient: False
            metrics: False
          - label: True
            loss: True
            activation: False
            gradient: False
            metrics: True
          - label: True
            loss: True
            activation: False
            gradient: False
            metrics: True
          - label: True
            loss: True
            activation: True
            gradient: True
            metrics: False
          - label: True
            loss: True
            activation: True
            gradient: True
            metrics: False
          - label: True
            loss: True
            activation: True
            gradient: True
            metrics: True
          - label: True
            loss: True
            activation: True
            gradient: True
            metrics: True
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv2d
          out_channels: 1000
          kernel_size:
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
