simulation:
  data:
    dataset_name: Texas
    batch_size: -1
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["features"],
          "y": element["label"]
        }
  federation:
    client_count: 10
    fraction_fit: 1.0
    local_rounds: 1
  model:
    optimizer_name: SingleLayerFedNL
    model_name: Logistic Regression
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
    model_architecture:
      - type: Linear
        in_features: 6169
        out_features: 100
attack:
  data_access: 1.0
#    steps:
#      - 1.0
#      - 1.0
#      - 1.0
#      - 1.0
#      - 0.1
#      - 0.1
  message_access: server
#    steps:
#      - server
#      - server
#      - server
#      - server
#      - client
#      - client
  aggregate_access: [1]
  repetitions: 0
  attack_simulation:
    batch_size: 512
#      steps:
#        - 512
#        - 16
#        - 256
#        - 4
#        - 512
#        - 16
    optimizer_name: Adam
    optimizer_parameters:
      eps: 0.0001
    model_architecture:
      components:
        label: True
        loss: True
        activation: False
        gradient: False
        metrics: False
#      components:
#        steps:
#          - label: True
#            loss: True
#            activation: False
#            gradient: False
#            metrics: False
#          - label: True
#            loss: True
#            activation: False
#            gradient: False
#            metrics: True
#          - label: True
#            loss: True
#            activation: True
#            gradient: True
#            metrics: False
#          - label: True
#            loss: True
#            activation: True
#            gradient: True
#            metrics: True
#          - label: True
#            loss: True
#            activation: False
#            gradient: False
#            metrics: False
#          - label: True
#            loss: True
#            activation: True
#            gradient: True
#            metrics: True
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv2d
          out_channels: 1000
          kernel_size:
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
