simulation:
  batch_size: 2
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 20
  optimizer:
    optimizer_name: FedNAG
    lr: 0.1
    momentum: 0.85
dataset:
  name: Texas
  preprocess_fn: |
    def preprocess_fn(element):
      return element
model:
  name: Logistic Regression
  criterion: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 6169
      out_features: 100
    - type: Softmax
      dim: -1
