simulation:
  data:
    dataset_name: MNIST
    batch_size: 1
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["image"].reshape(784) / 255.,
          "y": element["label"]
        }
    splitter:
      alpha: 1.0
      percent_non_iid: 25.0
  federation:
    client_count: 100
    fraction_fit: 0.1
    global_rounds: 1
    local_rounds: 1
  model:
    optimizer_name: FedAvg
    model_name: Logistic Regression
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      - type: Linear
        in_features: 784
        out_features: 10
      - type: Softmax
        dim: -1
attack:
  is_targeted: False
  data_access: all
  message_access: server
  shadow_model_amount: 2
  attack_simulation:
    batch_size: 64
    optimizer_name: FedAvg
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv3d
          out_channels: 1000
          kernel_size:
            - 1
            - 1
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
        - type: Sigmoid
