wandb_version: 1

dataset:
  desc: null
  value: MNIST
model:
  desc: null
  value: Logistic Regression
batch_size:
  desc: null
  value: -1
client_count:
  desc: null
  value: 4
fraction_fit:
  desc: null
  value: 1.0
learning_method:
  desc: null
  value: SGD
local_rounds:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711465875.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 30
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 30
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: server_round
      6:
      - 3
    - 1: accuracy
      5: 1
      6:
      - 1
      - 3
    - 1: loss
      5: 1
      6:
      - 1
      - 3
