simulation:
  batch_size: 16
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 10
  optimizer:
    optimizer_name: FedAdam
    local:
      lr: 0.2
    global:
      lr: 0.01
      betas:
        - 0.9
        - 0.999
      eps: 0.000000001
      weight_decay: 0.9999
dataset:
  name: ImageNet
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"] / 255.,
        "y": element["label"]
      }
model:
  name: ResNet50
  criterion: CrossEntropyLoss
  hub:
    repo_or_dir: 'pytorch/vision:v0.10.0'
    model: 'resnet50'
    pretrained: False
