attack:
  data_access_type: all
  update_access_type: server
  shadow_model_amount: 128 # Carlini 2022 Membership Inference Attacks from First Principles
  attack_model:
    fcn:
      - type: Dropout
        p: 0.2
      - type: Linear
        out_features: 128
      - type: ReLU
      - type: Dropout
        p: 0.2
      - type: Linear
        in_features: 128
        out_features: 64
      - type: ReLU
    encoder:
      - type: Dropout
        p: 0.2
      - type: Linear
        out_features: 256
      - type: ReLU
      - type: Dropout
        p: 0.2
      - type: Linear
        in_features: 256
        out_features: 128
      - type: ReLU
      - type: Dropout
        p: 0.2
      - type: Linear
        in_features: 128
        out_features: 64
      - type: ReLU
      - type: Dropout
        p: 0.2
      - type: Linear
        in_features: 64
        out_features: 1
      - type: ReLU
      - type: Sigmoid
    cnn:
      - type: Dropout
        p: 0.2
      - type: Conv3d
        out_channels: 1000
        kernel_size:
          - 1
          - 1
        stride: 1
      - type: ReLU
  simulation:
    batch_size: 64 # 64 and 128 are most efficient
    optimizer:
      optimizer_name: RMSprop
simulation:
  batch_size: 8
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 100
  local_rounds: 20
  optimizer:
    optimizer_name: Adam
    local:
      lr: 0.2
    global:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 0.000000001
      weight_decay: 0
dataset:
  name: ImageNet
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"] / 255.,
        "y": element["label"]
      }
model:
  name: ResNet50
  criterion: CrossEntropyLoss
  hub:
    repo_or_dir: 'pytorch/vision:v0.10.0'
    model: 'resnet50'
    pretrained: False
