simulation:
  batch_size: 10
  client_count: 1
  fraction_fit: 1.0
  global_rounds: 20
  local_rounds: 10
  optimizer:
    optimizer_name: SGD
    lr: 0.01
dataset:
  name: Cifar10
  splitter:
    alpha: 1
    percent_non_iid: 25
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": (element["img"] / 255.) - 0.5,
        "y": element["label"]
      }
model:
  name: DenseNet
  criterion: CrossEntropyLoss
  layers:

