simulation:
  batch_size: 10
  client_count: 1
  fraction_fit: 1.0
  global_rounds: 20
  learning_method:
    optimizer: SGD
    lr: 0.01
  local_rounds: 10
dataset:
  name: MNIST
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": (element["img"] / 255.) - 0.5,
        "y": element["label"]
      }
  splitter:
    alpha: 1
    percent_non_iid: 25
model:
  name: DenseNet
  criterion: CrossEntropyLoss
  layers:

