simulation:
  data:
    dataset_name: CIFAR10
    batch_size: 64
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["img"],
          "y": element["label"]
        }
  federation:
    client_count: 100
    fraction_fit: 0.1
    local_rounds: 4
  model:
    optimizer_name: FedNag
    model_name: ResNet18
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      lr: 0.01
      momentum: 0.9
    model_architecture:
      repo_or_dir: 'pytorch/vision:v0.10.0'
      model: 'resnet18'
      pretrained: False
      out_features: 10
attack:
  data_access: 1.0
  message_access: server
  aggregate_access: 1
  repetitions: 0
  attack_simulation:
    batch_size: 64
    optimizer_name: Adam
    optimizer_parameters:
      eps: 0.0001
    model_architecture:
      components:
        label: False
        loss: True
        activation: False
        gradient: False
        metrics: False
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv2d
          out_channels: 1000
          kernel_size:
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
        - type: Sigmoid
