simulation:
  batch_size: 1
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 8
  optimizer:
    optimizer_name: FedAdam
    local:
      lr: 0.1
    global:
      lr: 0.1
      betas:
        - 0.9
        - 0.999
      eps: 0.00000001
      weight_decay: 0.9999
dataset:
  name: Purchase
  preprocess_fn: |
    def preprocess_fn(element):
      return element
model:
  name: Logistic Regression
  criterion: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 600
      out_features: 100
    - type: Softmax
      dim: -1
