simulation:
  batch_size: 8
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 100
  local_rounds: 20
  optimizer:
    optimizer_name: FedNAG
    lr: 0.25
    momentum: 0.9
dataset:
  name: MNIST
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"].reshape(1, 28, 28) / 255.,
        "y": element["label"]
      }
model:
  name: CNN
  criterion: CrossEntropyLoss
  layers:
    - type: Conv2d
      in_channels: 1
      out_channels: 32
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Conv2d
      in_channels: 32
      out_channels: 64
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Flatten
      start_dim: 1
      end_dim: -1
    - type: Linear
      in_features: 3136
      out_features: 512
    - type: ReLU
    - type: Linear
      in_features: 512
      out_features: 10
    - type: Softmax
      dim: -1
