simulation:
  batch_size: 16
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 10
  optimizer:
    optimizer_name: FedAdam
    local:
      lr: 0.2
    global:
      lr: 0.01
      betas:
        - 0.9
        - 0.999
      eps: 0.000000001
      weight_decay: 0.9999
dataset:
  name: MNIST
  splitter:
    alpha: 1
    percent_non_iid: 25
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"].reshape(1, 28, 28) / 255.,
        "y": element["label"]
      }
model:
  name: CNN
  criterion: CrossEntropyLoss
  layers:
    - type: Conv2d
      in_channels: 1
      out_channels: 32
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Conv2d
      in_channels: 32
      out_channels: 64
      kernel_size: 5
      padding: 2
    - type: ReLU
    - type: MaxPool2d
      kernel_size: 2
      stride: 2
    - type: Flatten
      start_dim: 1
      end_dim: -1
    - type: Linear
      in_features: 3136
      out_features: 512
    - type: ReLU
    - type: Linear
      in_features: 512
      out_features: 10
    - type: Softmax
      dim: -1
