# Optimal 0.9147
simulation:
  data:
    dataset_name: MNIST
    batch_size: 1
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["image"].reshape(784) / 255.,
          "y": element["label"]
        }
  federation:
    client_count: 100
    fraction_fit: 0.01
    global_rounds: 2
    local_rounds: 1
  model:
    optimizer_name: FedAdam
    model_name: Logistic Regression
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      local:
        lr: 0.1
      global:
        lr: 0.1
        betas:
          - 0.9
          - 0.999
        eps: 0.00000001
        weight_decay: 0.9999
    model_architecture:
      - type: Linear
        in_features: 784
        out_features: 10
      - type: Softmax
        dim: -1
attack:
  data_access: all
  message_access: server
  repetitions: 10
  attack_simulation:
    batch_size: 64
    optimizer_name: FedAvg
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv3d
          out_channels: 1000
          kernel_size:
            - 1
            - 1
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
        - type: Sigmoid
