wandb:
  dataset_name: MNIST
  model_name: Logistic Regression
simulation:
  batch_size: -1
  client_count: 4
  fraction_fit: 1.0
  global_rounds: 1
  learning_method:
    optimizer: SGD
    lr: 0.05
  local_rounds: 10
dataset:
  name: MNIST
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"].reshape(784) / 255.,
        "y": element["label"]
      }
  splitter:
    alpha: 1
    percent_non_iid: 25
model:
  criterion:
    type: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 784
      out_features: 10
    - type: Softmax
      dim: 0
