simulation:
  batch_size: 16
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 20
  optimizer:
    optimizer_name: FedAdam
    local:
      lr: 0.25
    global:
      lr: 0.01
      betas:
        - 0.9
        - 0.999
      eps: 0.000000001
      weight_decay: 0.9999
dataset:
  name: Purchase
  preprocess_fn: |
    def preprocess_fn(element):
      return element
model:
  name: FCN
  criterion: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 600
      out_features: 200
    - type: Tanh
    - type: Linear
      in_features: 200
      out_features: 128
    - type: Tanh
    - type: Linear
      in_features: 128
      out_features: 100
    - type: Softmax
      dim: -1
