simulation:
  batch_size: 8
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 50
  optimizer:
    optimizer_name: FedNAG
    lr: 0.01
    momentum: 0.95
dataset:
  name: Purchase
  preprocess_fn: |
    def preprocess_fn(element):
      return element
model:
  name: FCN
  criterion: CrossEntropyLoss
  layers:
    - type: Linear
      in_features: 600
      out_features: 200
    - type: Tanh
    - type: Linear
      in_features: 200
      out_features: 128
    - type: Tanh
    - type: Linear
      in_features: 128
      out_features: 100
    - type: Softmax
      dim: -1
