simulation:
  batch_size: 8
  client_count: 100
  fraction_fit: 0.1
  global_rounds: 10
  local_rounds: 20
  optimizer:
    optimizer_name: FedAvg
    lr: 0.2
dataset:
  name: ImageNet
  preprocess_fn: |
    def preprocess_fn(element):
      return {
        "x": element["image"] / 255.,
        "y": element["label"]
      }
model:
  name: ResNet50
  criterion: CrossEntropyLoss
  hub:
    repo_or_dir: 'pytorch/vision:v0.10.0'
    model: 'resnet50'
    pretrained: False

