simulation:
  data:
    dataset_name: Purchase
    batch_size: 8
    preprocess_fn: |
      def preprocess_fn(element):
        return element
  federation:
    client_count: 100
    fraction_fit: 0.1
    global_rounds: 10
    local_rounds: 20
  model:
    optimizer_name: FedAvg
    model_name: FCN
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      lr: 0.25
    model_architecture:
      - type: Linear
        in_features: 600
        out_features: 200
      - type: Tanh
      - type: Linear
        in_features: 200
        out_features: 128
      - type: Tanh
      - type: Linear
        in_features: 128
        out_features: 100
      - type: Softmax
        dim: -1
attack:
  data_access: all
  message_access: server
  repetitions: 10
  attack_simulation:
    batch_size: 64
    optimizer_name: FedAvg
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      gradient_component:
        - type: Dropout
          p: 0.2
        - type: Conv3d
          out_channels: 1000
          kernel_size:
            - 1
            - 1
          stride: 1
        - type: ReLU
      fcn_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
      encoder_component:
        - type: Dropout
          p: 0.2
        - type: Linear
          out_features: 256
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 256
          out_features: 128
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 128
          out_features: 64
        - type: ReLU
        - type: Dropout
          p: 0.2
        - type: Linear
          in_features: 64
          out_features: 1
        - type: ReLU
        - type: Sigmoid
