simulation:
  data:
    dataset_name: MNIST
    batch_size: 1
    preprocess_fn: |
      def preprocess_fn(element):
        return {
          "x": element["image"].reshape(784) / 255.,
          "y": element["label"]
        }
  federation:
    client_count: 100
    fraction_fit: 0.1
    global_rounds: 10
    local_rounds: 20
  model:
    optimizer_name: FedAvg
    model_name: Logistic Regression
    criterion_name: CrossEntropyLoss
    optimizer_parameters:
      lr: 0.1
    model_architecture:
      - type: Linear
        in_features: 784
        out_features: 10
      - type: Softmax
        dim: -1
attack:
  is_targeted: True
  data_access: all
  message_access: server
  shadow_model_amount: 128
